<a href="https://colab.research.google.com/github/cc5547/DataAnalysis/blob/main/cc5547/2023_03_09_ch05_01%2B02_%EB%B3%B5%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#!pip install numpy
import numpy as np # 규칙, 규약

In [ ]:
np.array([1, 2, 3])

array([1, 2, 3])

In [ ]:
np.array((1, 2, 3))

array([1, 2, 3])

In [ ]:
np.array(range(1, 4))

array([1, 2, 3])

In [ ]:
np.array([int(c) for c in "123"])

array([1, 2, 3])

In [ ]:
arr = np.array([1, 2, 3])

In [ ]:
type(arr) # n-dimentinal array

numpy.ndarray

## 벡터화 연산

In [ ]:
a = list(range(10))
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
a + 10

TypeError: ignored

In [ ]:
a + [10]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
a * 2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
[v for v in a]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
[v + 2 for v in a]

[2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [ ]:
[v * 2 for v in a]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [ ]:
arr = np.arange(10) # np.array(range(10))
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr + 2 # 배열(np.ndarray)에서 산술 연산자는 각각의 원소들에 대해서 계산 진행

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
np.ones_like(arr) * 2

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
arr + np.ones_like(arr) * 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
arr * 5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
(((arr * 5) // 2) - 1) % 7

array([6, 1, 4, 6, 2, 4, 0, 2, 5, 0])

In [ ]:
arr == 5

array([False, False, False, False, False,  True, False, False, False,
       False])

In [ ]:
arr[arr == 5]

array([5])

In [ ]:
arr[arr > 5]

array([6, 7, 8, 9])

In [ ]:
np.where(arr > 5)

(array([6, 7, 8, 9]),)

In [ ]:
arr2 = np.arange(6, 25, 2)
arr2

array([ 6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [ ]:
np.where(arr2 % 3 == 0)

(array([0, 3, 6, 9]),)

In [ ]:
arr2[np.where(arr2 % 3 == 0)] # arr2[arr2 % 3 == 0]

array([ 6, 12, 18, 24])

In [ ]:
arr2[[0] * 5]

array([6, 6, 6, 6, 6])

In [ ]:
arr[(arr > 5) | (arr % 2 == 0)]

array([0, 2, 4, 6, 7, 8, 9])

In [ ]:
arr[(arr > 5) & (arr % 2 == 0)]

array([6, 8])

* https://www.facebook.com/groups/codingeverybody/posts/873281936045677/

```
! - bang(뱅)Exclamation Point(엑스클러메이션 포인트)
# - Crosshatch(크로스해치), Sharp(샵), Pound Sign(파운드사인)
$ - Dollar Sign (달러사인)
% - Percent Sign(퍼센트사인)
@ - At Sign (앳 사인), Commercial At(커머셜 앳)
& - Ampersand(앰퍼샌드) snowman
' - single quote(싱글쿼트) Apostrophe(어퍼스트로피), single quotation mark
" - double quote(더블쿼트)Quotation Mark(쿼테이션마크) , Double Quotation Mark
* - Asterisk(애스터리스크)
. - Period(피리어드), Full Stop(풀스탑)
/ - Slash (슬래시), Virgule(버귤)
\ - Back Slash(백슬래시)
: - Colon (콜론)
; - Semicolon(세미콜론)
^ - Circumflex(서컴플렉스), Caret(캐럿)
`(<<~이랑 같이 있는 넘) - Back Quote(백쿼트)Grave(그레이브)
{} - Brace(브레이스) (중괄호) curly braces/curly brackets
[] - Bracket(브래킷) (대괄호) brackets/square brackets
() - Parenthesis(퍼렌씨시스) (괄호)
| - Vertical Bar(버티컬바)
~ - Tilde (틸드)
= - Equal sign(이퀄사인)
+ - Plus Sign(플러스사인)
- - Minus Sign(마이너스사인)Hyphen(하이픈),Dash(대시)
_ - Underscore(언더스코어),Underline(언더라인)
< - Less Than Sign(레스댄 사인), Left Angle Bracket(레프트 앵글브래킷)
> - Greater Than Sign(그레이터댄 사인), Right Angle Bracket(라이트 앵글 브래킷)
? - Question Mark(물음표)
```

In [ ]:
# ndarray
np.array([[1, 2, 3, 4], [1, 2, 3, 4]]) # 행들 간의 길이(열의 크기기) 같아야함

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [ ]:
np.array([[1, 2, 3, 4], [1, 2, 3]])

<ipython-input-46-e6426570ace6>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[1, 2, 3, 4], [1, 2, 3]])


array([list([1, 2, 3, 4]), list([1, 2, 3])], dtype=object)

In [ ]:
a1 = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])
a1

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [ ]:
a1[1, 1]

2

In [ ]:
a2 = np.array([[1, 2, 3, 4], [1, 2, 3]])
a2[1, 1]

<ipython-input-49-b813f9fe8871>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a2 = np.array([[1, 2, 3, 4], [1, 2, 3]])


IndexError: ignored

In [ ]:
a1.ndim, a1.shape

(2, (2, 4))

In [ ]:
a2.ndim, a2.shape

(1, (2,))

In [ ]:
m = np.array([[1,2], [3,4]])
m2 = np.array((range(2,4), range(5,7)))
print(m)
print(m2)

[[1 2]
 [3 4]]
[[2 3]
 [5 6]]


In [ ]:
t = np.array([
    [
        [1, 4, 5, 6],
        [1, 4, 5, 6],
        [1, 4, 5, 6]
    ],
    [
        [1, 4, 5, 6],
        [1, 4, 5, 6],
        [1, 4, 5, 6]
    ],
])
t

array([[[1, 4, 5, 6],
        [1, 4, 5, 6],
        [1, 4, 5, 6]],

       [[1, 4, 5, 6],
        [1, 4, 5, 6],
        [1, 4, 5, 6]]])

In [ ]:
t.ndim, t.shape

(3, (2, 3, 4))

In [ ]:
a = np.arange(10).reshape(2, 4) # 10이 나와야하는데 8 나왔음...
# shape에 들어가는 매개변수들은, 모두 곱했을 때 전체 원소 크기가... (-1)

ValueError: ignored

In [ ]:
a = np.arange(10).reshape(5, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
b = a
b[0,1] = 9

In [ ]:
print(a)
print(b)

[[0 9]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 9]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
c = a.copy()
c[2, 1] = -99
print(a)
print(c)

[[0 9]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[  0   9]
 [  2   3]
 [  4 -99]
 [  6   7]
 [  8   9]]


In [ ]:
a = np.arange(1, 100, 25)
a

array([ 1, 26, 51, 76])

In [ ]:
a[3], a[-1], a[a.shape[0]-1]

(76, 76, 76)

In [ ]:
# , (comma) [][]
m = np.arange(6).reshape((2, 3))
m

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
m[0, 0], m[0, 1]

(0, 1)

In [ ]:
m.ndim, m.shape

(2, (2, 3))

In [ ]:
m[-2, 0], m[-2, -1]

(0, 2)

In [ ]:
m[m.shape[0]-2, 0], m[m.shape[0]-2, m.shape[1]-1]

(0, 2)

In [ ]:
d1, d2 = m.shape # d1 : 행 차원의 길이, d2: 열 차원의 길이
row_length, column_length = m.shape

In [ ]:
m[d1-2, 0], m[d1-2, d2-1]
m[row_length-2, 0], m[row_length-2, column_length-1]

(0, 2)

In [ ]:
# 1차원의 배열의 슬라이싱 = 리스트의 슬라이싱과 같다
a[1:2]

array([26])

In [ ]:
a2 = np.arange(0, 100, 10)
a2

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
a2[1:10:2], a2[10::-1], a2[::-1], a2[:]

(array([10, 30, 50, 70, 90]),
 array([90, 80, 70, 60, 50, 40, 30, 20, 10,  0]),
 array([90, 80, 70, 60, 50, 40, 30, 20, 10,  0]),
 array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]))

In [ ]:
m

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
m[0,:], m[0]

(array([0, 1, 2]), array([0, 1, 2]))

In [ ]:
m[:,0]
print(m[:,0:1])

[[0]
 [3]]


https://www.w3schools.com/python/numpy/default.asp

## 배열의 자료형

In [ ]:
x = np.array([1, 2, 3])
x.dtype

dtype('int64')

In [ ]:
x = np.array([1.0, 2.0, 3.0])
x.dtype

dtype('float64')

In [ ]:
x = np.array([1, 2.0, 3])
x.dtype

dtype('float64')

In [ ]:
x = np.array([1, 2.0, "3"])
x.dtype

dtype('<U32')

In [ ]:
x = np.array([1, 2, 3], dtype='i')
x2 = np.array([1, 2, 3], dtype=int)
print(x, x.dtype)
print(x2, x2.dtype)

[1 2 3] int32
[1 2 3] int64


In [ ]:
x = np.array([1, 2, 3], dtype='f')
x2 = np.array([1, 2, 3], dtype=float)
print(x, x.dtype)
print(x2, x2.dtype)

[1. 2. 3.] float32
[1. 2. 3.] float64


In [ ]:
x = np.array([1, 2, 3.5], dtype='i')
print(x, x.dtype)

[1 2 3] int32


In [ ]:
x = np.array([1, 2, "안녕"], dtype='i')
print(x, x.dtype)

ValueError: ignored

In [ ]:
a = np.zeros(5)
b = np.array([0, 1, 0, 1, 0]) # 0 / 0 -> nan not a number. -> na.
a / b, b / a # inf -> infinity

<ipython-input-116-938594f7caf7>:3: RuntimeWarning: invalid value encountered in true_divide
  a / b, b / a
<ipython-input-116-938594f7caf7>:3: RuntimeWarning: divide by zero encountered in true_divide
  a / b, b / a


(array([nan,  0., nan,  0., nan]), array([nan, inf, nan, inf, nan]))

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
a = np.arange(10).reshape(2, 5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
np.zeros_like(a)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
np.ones_like(a)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.empty((2, 5))

array([[2.72459575e-316, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 2.41907520e-312],
       [2.96014213e-032, 1.16193095e+165, 6.81158733e-091,
        1.31241021e-071, 6.32210368e-310]])

In [ ]:
np.linspace(10, 100, 5) # y = x

array([ 10. ,  32.5,  55. ,  77.5, 100. ])

In [ ]:
np.logspace(0.1, 1, 5) # y = logx

array([ 1.25892541,  2.11348904,  3.54813389,  5.95662144, 10.        ])

In [ ]:
A = np.arange(1, 7).reshape(2, 3)
A

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
A.ndim, A.shape

(2, (2, 3))

In [ ]:
A2 = A.T
A2

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
A2.ndim, A2.shape

(2, (3, 2))

In [ ]:
A, A.flatten(), A.ravel()

(array([[1, 2, 3],
        [4, 5, 6]]), array([1, 2, 3, 4, 5, 6]), array([1, 2, 3, 4, 5, 6]))

In [ ]:
t = np.arange(30).reshape(3, 5, 2)
t

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]]])

In [ ]:
t.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
x = np.arange(5)
print(x, x.ndim, x.shape)
x2 = x[:, np.newaxis]
print(x2, x2.ndim, x2.shape)
x3 = x[np.newaxis,:]
print(x3, x3.ndim, x3.shape)

[0 1 2 3 4] 1 (5,)
[[0]
 [1]
 [2]
 [3]
 [4]] 2 (5, 1)
[[0 1 2 3 4]] 2 (1, 5)
